---
- name: Install and restart Nginx
  hosts: all
  become : yes
  become_user: root
  tasks:

    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: stop nginx
      service:
        name: nginx
        state: stopped


<<<<<<<<<<<<<<<<<<<<<<<<<<<<< nginx start>>>>
---
- name: Install Nginx
  hosts: dev
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: start nginx
      service:
        name: nginx
        state: started
